language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
before_script:
  - cd proj
  - python manage.py migrate
script:
  - flake8 proj
  - coverage run manage.py test
after_success:
  - coveralls